trigger:
    - master

strategy:
    matrix:
        linux:
            imageName: 'ubuntu-16.04'
        windows:
            imageName: 'vs2017-win2016'

pool:
    vmImage: $(imageName)

variables:
    buildConfiguration: 'Release'

steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'Build All'
    - script: dotnet test --configuration $(buildConfiguration)
      displayName: 'Test'